apiVersion: v1
kind: Pod
metadata:
  name: memtoobig
spec:
  containers:
  - name: mem-too-big
    image: vish/stress
    resources:
      limits:
        memory: "1000Gi"
      requests:
        memory: "1000Gi"
    args:
    - -mem-total
    - 150Mi
    - -mem-alloc-size
    - 10Mi
    - -mem-alloc-sleep
    - 1s
