apiVersion: v1
kind: Pod
metadata:
  name: init-demo
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html
  initContainers:
  - name: install
    image: busybox
    command: ["wget"]
    args: ["-O","/work-dir/index.html","http://www.componentsoft.io"]
    volumeMounts:
    - name: htmldir 
      mountPath: "/work-dir"
  volumes:
  - name: htmldir
    emptyDir: {}
