apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: failure-domain.k8s.io/zone
            operator: In
            values:
            - zone1
  containers:
  - name: with-node-affinity
    image: k8s.gcr.io/pause:2.0
