apiVersion: v1
kind: Service
metadata:
  name: node-svc2
  labels:
    app: echosrv
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      targetPort: 9376
  selector:
    app: echosrv

