apiVersion: v1
kind: Pod
metadata:
  name: vol-pod-pvc
  namespace: default
spec:
 containers:
 - image: ubuntu
   name: vol-ubuntu
   command: ["sleep","3600"]
   volumeMounts:
   - name: pvc-vol
     mountPath: /data
 restartPolicy: Always
 volumes:
 - name: pvc-vol
   persistentVolumeClaim:
    claimName: glusterfs-claim 
