apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: glusterfs-claim
 namespace: default
spec:
 accessModes:
  - ReadWriteMany
 resources:
  requests:
   storage: 1Gi
  limits:
   storage: 2Gi
 storageClassName: gluster
