apiVersion: v1
kind: Pod
metadata:
  name: vol-pod-host
  namespace: default
spec:
 containers:
 - image: ubuntu
   name: vol-ubuntu
   command: ["sleep","3600"]
   volumeMounts:
   - name: local
     mountPath: /data
 restartPolicy: Always
 volumes:
 - name: local
   hostPath:
     path: /var/tmp/duckademy
     type: DirectoryOrCreate
