apiVersion: v1
kind: Pod
metadata:
  name: vol-pod-emptydir
  namespace: default
spec:
 containers:
 - image: ubuntu
   name: vol-ubuntu
   command: ["sleep","3600"]
   volumeMounts:
   - name: tempdir
     mountPath: /data
 restartPolicy: Always
 volumes:
 - name: tempdir
   emptyDir: {}
