apiVersion: v1
kind: PersistentVolume
metadata:
 name: glustervol
spec:
 capacity:
  storage: 10Gi
 accessModes:
  - ReadWriteMany
 storageClassName: gluster
 glusterfs:
  endpoints: "gluster-cluster"
  path: "/gv0"
