apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginxredis--deployment
spec:
  selector:
    matchLabels:
      app: nginx
      db: redisdb
  replicas: 2
  template:
    metadata:
      labels:
       app: nginx
       db: redisdb
    spec:
     containers:
     - name: nginx
       image: nginx:1.12
       ports:
       - containerPort: 80
     - name: redis
       image: redis
