apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-scheduled
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
   spec:
    template:
     spec:
      containers:
      - name: counter
        image: busybox
        command: ["sleep", "15"]
      restartPolicy: OnFailure
    backoffLimit: 3
    #concurrencyPolicy: Allow
    #concurrencyPolicy: Forbid
    #concurrencyPolicy: Replace
