apiVersion: batch/v1
kind: Job
metadata:
  name: counter-job
spec:
  completions: 10
  parallelism: 2
  template:
    spec:
      containers:
      - name: counter
        image: busybox
        command: ["sleep", "15"]
      restartPolicy: Never
  backoffLimit: 3
